# Copyright (c) 2023-2024 MDSANIMA DEV. All rights reserved.
# Licensed under the MIT license.

# This file is used for Dependabot that automatically updates the packages to the latest release versions.
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

# Dependabot setup
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Warsaw
      time: "12:30"
    labels: [dependencies, python, pip]
