# Copyright (c) 2024 MDSANIMA DEV. All rights reserved.
# Licensed under the MIT license.

# Automatically keep the dependencies and packages updated to the latest version.
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/

# Dependabot setup
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Warsaw
      time: "12:30"
    labels: [dependencies, python, pip]
