# The project in the repository is open-source and free to use, but if you want
# to support the project, you can sponsor it through PayPal or in other ways.
# GitHub Sponsors option for funding this project with a link to the PayPal.

---
custom: "https://paypal.me/mdsanima"
