# Default and custom labels for this repository, used for pull requests and
# issues.  All labels defined here are synced with the repository using GitHub
# Actions workflow in `.github/workflows/labeler.yaml` file.  The workflow is
# triggered when this file is updated and pushed to main branch.

---
# Default
- name: bug
  color: B60205
  description: Something isn't working
- name: documentation
  color: 0052CC
  description: Improvements or additions to documentation
- name: duplicate
  color: D93F0B
  description: This issue or pull request already exists
- name: enhancement
  color: 006B75
  description: New feature or request
- name: good first issue
  color: 5319E7
  description: Good for newcomers
- name: help wanted
  color: 9A05D2
  description: Extra attention is needed
- name: invalid
  color: F60029
  description: This doesn't seem right
- name: question
  color: 4D5D10
  description: Further information is requested
- name: wontfix
  color: FBCA04
  description: This will not be worked on

# Custom
- name: ci
  color: FBCA04
  description: Continuous integration tools
- name: database
  color: 097BA1
  description: Database task
- name: db
  color: 98C3E1
  description: Database configuration
- name: dependencies
  color: 0033FF
  description: Update dependencies in the project
- name: deps
  color: 2B3999
  description: Dependencies updates
- name: deployment
  color: 0F3150
  description: Kubernetes deployment configuration
- name: dev
  color: 0E8A86
  description: Development environment
- name: devel
  color: F91386
  description: Development task
- name: docker
  color: 0086CC
  description: Docker configuration
- name: docs
  color: 20967C
  description: Documentation updates
- name: done
  color: A1E752
  description: Task is completed
- name: epic
  color: 7802EE
  description: Cool idea for a new feature
- name: feature
  color: 0086CC
  description: New feature
- name: kubernetes
  color: 12488A
  description: Kubernetes configuration
- name: nodejs
  color: 596E3D
  description: Node.js configuration
- name: npm
  color: ABB062
  description: Update Node.js dependencies
- name: pip
  color: 2E79F8
  description: Update Python dependencies
- name: prod
  color: 2D13F1
  description: Production environment
- name: python
  color: 006B75
  description: Python configuration
- name: service
  color: 1ED5B6
  description: Kubernetes service configuration
- name: task
  color: 089DB8
  description: New task
- name: workflow
  color: FD582D
  description: GitHub Actions workflow configuration

# General
- name: build
  color: 074B2B
  description: Build system or external dependencies
- name: chore
  color: 706ED7
  description: Regular maintenance
- name: performance
  color: E36900
  description: Optimize performance
- name: refactor
  color: 896CD6
  description: Code refactoring
- name: revert
  color: E79263
  description: Revert changes
- name: security
  color: D93F00
  description: Security vulnerability
- name: style
  color: 4686B3
  description: Code formatting
- name: test
  color: 8642B2
  description: Add or update tests
