# Maintain a consistent coding style across the entire project by maintaining a consistent style.

# This is simple configuration file for code styling in lua language.

line_endings = "Unix"
quote_style = "AutoPreferDouble"

call_parentheses = "None"

indent_type = "Spaces"
indent_width = 2
column_width = 100
