# Copyright (c) 2023-2024 MDSANIMA DEV. All rights reserved.
# Licensed under the MIT license.

# This file is for linting commit messages with commitlint GitHub action workflow on PR.
# Documentation: https://github.com/wagoid/commitlint-github-action/#commitlint-github-action


name: Run Commitlint on PR

on:
  pull_request:

jobs:
  commitlint-on-pr:
    name: Run Commitlint on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ./.commitlintrc
