# Lints commit messages on pull requests that follow the configuration defined
# in the `.commitlint.yaml` file for conventional commit messages.

---
name: Lint commit messages

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlint.yaml
