# Copyright (c) 2024 MDSANIMA DEV. All rights reserved.
# Licensed under the MIT license.

# Syncing GitHub repository labels defined in the YAML configuration file.
# Documentation: https://github.com/Financial-Times/github-label-sync/

# Workflow setup
name: Sync Repository Labels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labeler.yml

permissions: write-all

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run labeler to sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
